### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by PedroPMS** [robersonfaria/laravel-database-schedule#10]
Hello.

I'm trying translate the UI to portuguese creating a file like `schedule.php` in my resources/lang/pt_BR folder, and this is not working. If I go to your package folder in vendor and add a pt_BR folder with my translations, it works. 

Anyway, I forked the project to add the pt_BR folder directly to your project and already do the translations. I'm sending the PR, this can help those who have projects in pt_BR

**Comment by PedroPMS** [comment]
I found the problem, I did `php artisan vendor:publish --provider="RobersonFaria\DatabaseSchedule\DatabaseSchedulingServiceProvider" --tag="config"` like the docs explain, but doesn't `php artisan vendor:publish --provider="RobersonFaria\DatabaseSchedule\DatabaseSchedulingServiceProvider"`, after this the translation works.

**Comment by robersonfaria** [comment]
Thank you very much for your contribution. I already approved the pull request.
