### ISSUE TITLE
Problem in request to create a schedule

### ISSUE THREAD

**Issue by PedroPMS** [robersonfaria/laravel-database-schedule#12]
Hello,

I have a command that have two arguments, I want to create a schedule passing just the first, but the request is sending all, like the image shows. 
Because of this, when cron runs, the method in Schedule model `mapArguments` break. I can resolve this is backend but I think is also a problem in the frontend that send invalid data.

I could resolve this too, but I'm terrible at frontend 😅.

![image](https://user-images.githubusercontent.com/48099126/115406431-8b24b500-a1c5-11eb-887b-53883a4f52db.png)

**Comment by robersonfaria** [comment]
Ok @PedroPMS, your pull request resolves and closes this issue.

Thank you very much for your contribution.
