### ISSUE TITLE
Duplicate output when send mail 

### ISSUE THREAD

**Issue by PedroPMS** [robersonfaria/laravel-database-schedule#15]
When you put an email to receive the output of the scheduled command, this out put is registred an sended twice. 

![image](https://user-images.githubusercontent.com/48099126/122426638-c72a8b00-cf66-11eb-9f34-520b54049450.png)

To reproduce the error, run the command without send mail option, after that register an email in the command and run it again.

**Comment by PedroPMS** [comment]
PHP 7.4.18
Laravel 8.34.0

**Comment by robersonfaria** [comment]
@PedroPMS 
I've already managed to fix this situation, I'm seeing the issue of sending a successful email in case of error and sending the two fixes together.

**Comment by PedroPMS** [comment]
> @PedroPMS
> I've already managed to fix this situation, I'm seeing the issue of sending a successful email in case of error and sending the two fixes together.

Ok, thanks.

**Comment by robersonfaria** [comment]
I couldn't find a solution for sending duplicate emails in case of failure, but I'll do some research if I can find something for that.

But anyway I just published a version ([1.0.21](https://github.com/robersonfaria/laravel-database-schedule/releases/tag/1.0.21)) with your changes and some other fixes of mine.

I will close this issue and open another one with the issue of duplicate shipments.
