### ISSUE TITLE
Is possible to add stop run current job when get false from before url?

### ISSUE THREAD

**Issue by zachary** [robersonfaria/laravel-database-schedule#23]
As the subject, thanks

**Comment by robersonfaria** [comment]
It's a case that I haven't really tested, I'll need to take some time to test it and see how it's working.
Did you just try to make a `return false`?

**Comment by zachary** [comment]
Yes, I tried it but the job still keep running

**Comment by robersonfaria** [comment]
@zachary Sorry for the delay, but I ran some tests now and it works the way it should

**Comment by robersonfaria** [comment]
Issue closed for lack of information on how to reproduce the error.
