### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by robersonfaria** [robersonfaria/laravel-database-schedule#44]
Various modifications and additions of new functionality have been made, it is necessary to update the documentation(README) to reflect all existing functionality.

If anyone can contribute I appreciate it.

**Comment by PedroPMS** [comment]
Can you list all the new functionalities that are not documentated?

**Comment by robersonfaria** [comment]
This is work I need to stop to do, I need to open approved pull requests and document the changes. I don't remember everything that was done, it ended up being disorganized.
We had some interface changes and new features.
