### ISSUE TITLE
Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### ISSUE THREAD

**Issue by zachary** [robersonfaria/laravel-database-schedule#47]
If try to pause and resume it, it will be crushed like this.

thanks

**Comment by zachary** [comment]
I fixed this issue 

![image](https://user-images.githubusercontent.com/92367/147705451-10bc085c-4f0b-4580-b414-6bea30d117f3.png)

**Comment by robersonfaria** [comment]
First, sorry for the delay in responding, I was on vacation.

Second, I couldn't understand the problem you solved, if you can explain better what the problem was and open a pull request with the fix I would be grateful.

Thanks.
