### ISSUE TITLE
Setting verbosity not possible?

### ISSUE THREAD

**Issue by LMCom** [robersonfaria/laravel-database-schedule#48]
Hi, this might be a really stupid question, but I cannot seem to find a way to specify the verbosity. There is neither a dropdown nor a generic input where I could specify additional parameters like "-vv".
Good logging is pretty important for my use case.

**Comment by LMCom** [comment]
There is a custom command for executing anything on the shell. It's a workaround, though, and looks a bit ugly.

**Comment by robersonfaria** [comment]
Hi @LMCom , it's really something I've never needed, but I believe it's something totally possible to implement, I'll put it on the project roadmap, if you want to contribute a pull request I'll be grateful.

Thanks.

**Comment by thyseus** [comment]
Its a year later, but i think i have a very simple workaround (or even solution?):

https://github.com/robersonfaria/laravel-database-schedule/pull/57

**Comment by robersonfaria** [comment]
@thyseus Very nice, really quite simple solution.
I saw that the tests broke but it doesn't seem to be a problem with the change. It seems to be something with the version of PHP used in the test, I'll take a closer look at this later.

Thanks a lot for the PR.
