### ISSUE TITLE
Add ability to schedule server commands instead of artisan

### ISSUE THREAD

**Issue by scryba** [robersonfaria/laravel-database-schedule#54]
for example to schedule the command:

`whoami`

to run on the server.

**Comment by thyseus** [comment]
This is already possible. Maybe a little bit hidden. See:

https://github.com/robersonfaria/laravel-database-schedule/pull/3

You can choose "custom" under the Command Dropdown and enter any system command there.

**Comment by scryba** [comment]
wow! great thanks this is a very helpful package so far. I have not found any that has this option.
