### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by LemonWipe** [robersonfaria/laravel-database-schedule#65]
Is there any plan to make this compatible with Laravel 11?

**Comment by roberson-rokah** [comment]
Yes, Laravel Swift already sent me the PR for this fix, but I haven't been able to review it yet if it won't break anything, I'll try to look at it today, to release it

#64

**Comment by robersonfaria** [comment]
Yes, Laravel Swift already sent me the PR for this fix, but I haven't been able to review it yet if it won't break anything, I'll try to look at it today, to release it

PR #64

**Comment by LemonWipe** [comment]
That's awesome, thanks for the update. I love this package!

**Comment by robersonfaria** [comment]
Version 1.4.0 released with support for laravel 11

I wasn't able to test it thoroughly, but in principle the lib is still functional, if you find any problems please let us know.
