### ISSUE TITLE
Add PHP 8 support

### ISSUE THREAD

**Issue by NKazantsev** [robersonfaria/laravel-database-schedule#9]
Hi, please add PHP 8 support

robersonfaria/laravel-database-schedule[1.0.0, ..., 1.0.15] require php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by robersonfaria** [comment]
I had not been able to test with PHP8 yet, I just ran some tests and updated the package requirements, now it is possible to use with PHP8.

If you encounter any problems using PHP8, please let me know.

Thanks.
